name: vUSDC with AaveStrategy
on: [pull_request]

jobs:
  vusdc-aave-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    env:
      NODE_URL: ${{secrets.NODE_URL}}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          token: ${{secrets.VESPER_CI_TOKEN}}
          submodules: true
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Run npm install with node v${{ matrix.node }}
        run: npm install
      - name: Running tests of vUSDC pool with AaveStrategy
        run: npm test "test/vusdc-aave.js"
